name: Cypress test in Git
on: [push]
jobs:
  cypress-run:
    name: Test1
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   env: # Or as an environment 
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      - name: test
        env: # Or as an environment 
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "$USERNAME"
        # with:
        #   build: npm i --legacy-peer-deps
        #   start: npm run cypress-run 
      - name: npm run deploy
        run: |
          export GIT_USER=${{secrets.USERNAME}}
          echo "$GIT_USER"