name: Cypress test in Git
on: [push]
jobs:
  cypress-run:
    name: Test1
    runs-on: ubuntu-20.04
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env: # Or as an environment 
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        with:
          working-directory: ${{ github.workspace }}
          install-command: npm i --legacy-peer-deps
          # build: npm i --legacy-peer-deps
          start: npm run cypress-run "cypress/integration/Test_specs/SalesForce.spec.ts --config-file stage-config.json"
      # - name: test
      #   env: # Or as an environment 
      #     USERNAME: ${{ secrets.USERNAME }}
      #     PASSWORD: ${{ secrets.PASSWORD }}
      #   run: |
      #     echo "$USERNAME"
        