name: Automation Tests
on:
  push:
    branches:
      - master
jobs:
  playwright-run:
    name: "Playwright tests"
    runs-on: ubuntu-latest
    environment: test
    container:
      image: mcr.microsoft.com/playwright:v1.27.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run your tests
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          PASS: ${{ secrets.PASS }}
          HAPPO_ENABLED: ${{ secrets.HAPPO_ENABLED }}
          HAPPO_API_SECRET: ${{ secrets.HAPPO_API_SECRET }}
          HAPPO_API_KEY: ${{ secrets.HAPPO_API_KEY }}
        run: STAGING=\"1\" npx playwright test
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: ${{ github.workspace }}/playwright-report
  cypress-run:
    name: "Cypress tests"
    runs-on: ubuntu-20.04
    environment: test
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm run deploy
        run: npm install
      - name: Cypress run
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_username: ${{ secrets.USERNAME }}
          CYPRESS_password: ${{ secrets.PASSWORD }}
        with:
          browser: chrome
          working-directory: ${{ github.workspace }}
          start: npm run cypress-run cypress/integration/Test_Specs/SalesForce.spec.ts --config-file cypress.json
